const createEntity = () => ({
  list: async () => [],
  filter: async () => [],
  create: async (data) => ({ id: 'demo-id', ...data }),
  update: async (id, data) => ({ id, ...data }),
  delete: async () => true,
});

export const base44 = {
  auth: {
    me: async () => ({
      id: 'demo-user',
      email: 'demo@dishcore.com',
      name: 'Demo User',
      role: 'user',
    }),
    logout: async () => {},
    updateMe: async () => {},
    list: async () => [],
    User: {
      list: async () => [],
      update: async (id, data) => ({ id, ...data }),
    },
  },
  entities: {
    UserProfile: createEntity(),
    Dish: createEntity(),
    MealPlan: createEntity(),
    MealLog: createEntity(),
    GroceryList: createEntity(),
    BodyMeasurement: createEntity(),
    BodyGoal: createEntity(),
    DishReview: createEntity(),
    SharedContent: createEntity(),
    UserProgress: createEntity(),
    Challenge: createEntity(),
    ChallengeProgress: createEntity(),
    StudioProfile: createEntity(),
    AdaptiveMenu: createEntity(),
    WearableData: createEntity(),
    ForumTopic: createEntity(),
    ForumReply: createEntity(),
    CommunityGroup: createEntity(),
    GroupMembership: createEntity(),
    UserFollowing: createEntity(),
    ActivityFeed: createEntity(),
    Goal: createEntity(),
    AccountabilityPartnership: createEntity(),
    WaterLog: createEntity(),
    FavoriteRecipe: createEntity(),
    BarcodeProduct: createEntity(),
    NotificationPreference: createEntity(),
    Notification: createEntity(),
    UserReport: createEntity(),
    SupportTicket: createEntity(),
    ContentSubmission: createEntity(),
    SLAConfig: createEntity(),
    TicketAutomation: createEntity(),
    ChatbotFAQ: createEntity(),
    ContentTemplate: createEntity(),
    Webhook: createEntity(),
    EmailTemplate: createEntity(),
  },
  functions: {
    invoke: async () => ({}),
  },
  integrations: {
    Core: {
      InvokeLLM: async () => ({ output: 'Demo response from DishCore stub' }),
      SendEmail: async () => ({ success: true }),
      UploadFile: async () => ({ file_url: '' }),
      GenerateImage: async () => ({ url: '' }),
      ExtractDataFromUploadedFile: async () => ({ data: {} }),
      CreateFileSignedUrl: async () => ({ url: '' }),
      UploadPrivateFile: async () => ({ file_url: '' }),
    },
  },
};
