
import React, { useState } from 'react';
import { base44 } from "@/api/base44Client";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Share2, Download, Link2, Check, Loader2 } from "lucide-react";
import { toast } from "sonner";
import { updateUserProgress } from "../gamification/progressUtils";

export default function ShareMealPlanDialog({ open, onClose, plan }) {
  const [description, setDescription] = useState('');
  const [shareUrl, setShareUrl] = useState('');
  const [isExporting, setIsExporting] = useState(false);

  const queryClient = useQueryClient(); // Initialize queryClient

  const shareToComm = useMutation({
    mutationFn: async (data) => {
      return await base44.entities.SharedContent.create(data);
    },
    onSuccess: async (result) => {
      const url = `${window.location.origin}/community/${result.id}`;
      setShareUrl(url);
      toast.success('Shared to community!');
      
      // Award points for sharing
      const progressResult = await updateUserProgress(null, { type: 'content_shared' });
      if (progressResult && progressResult.pointsEarned) { // Ensure progressResult is not null/undefined
        toast.success(`+${progressResult.pointsEarned} points!`);
      }
      queryClient.invalidateQueries(['userProgress']);
    },
  });

  const handleShareToCommunity = () => {
    shareToComm.mutate({
      content_type: 'meal_plan',
      title: plan.name,
      description: description || plan.rationale,
      content_data: plan,
      is_public: true
    });
  };

  const handleCopyLink = () => {
    navigator.clipboard.writeText(shareUrl);
    toast.success('Link copied to clipboard!');
  };

  const handleExportPDF = async () => {
    setIsExporting(true);
    try {
      const pdfContent = `
MEAL PLAN: ${plan.name}

${plan.rationale}

${plan.days.map((day, idx) => `
DAY ${idx + 1} - ${new Date(day.date).toLocaleDateString()}
Total: ${day.total_calories} kcal | P: ${day.total_protein}g | C: ${day.total_carbs}g | F: ${day.total_fat}g

${day.meals.map(meal => `  • ${meal.meal_type.toUpperCase()}: ${meal.dish_name} (${meal.calories} kcal)`).join('\n')}
`).join('\n')}

Generated by DishCore - biomathcore.com
      `.trim();

      const blob = new Blob([pdfContent], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${plan.name.replace(/\s+/g, '_')}.txt`;
      a.click();
      URL.revokeObjectURL(url);
      toast.success('Meal plan exported!');
    } catch (error) {
      toast.error('Export failed');
    }
    setIsExporting(false);
  };

  return (
    <Dialog open={open} onOpenChange={onClose}>
      <DialogContent className="max-w-md" style={{ background: 'var(--surface)', borderColor: 'var(--border)' }}>
        <DialogHeader>
          <DialogTitle style={{ color: 'var(--text-primary)' }}>
            Share Meal Plan
          </DialogTitle>
        </DialogHeader>

        <div className="space-y-4 pt-4">
          {!shareUrl ? (
            <>
              <div>
                <Label style={{ color: 'var(--text-secondary)' }}>Add a message (optional)</Label>
                <Textarea
                  placeholder="Share why this plan works for you..."
                  value={description}
                  onChange={(e) => setDescription(e.target.value)}
                  rows={3}
                  className="mt-2"
                  style={{ background: 'var(--background)', borderColor: 'var(--border)', color: 'var(--text-primary)' }}
                />
              </div>

              <div className="space-y-2">
                <Button
                  onClick={handleShareToCommunity}
                  disabled={shareToComm.isPending}
                  className="w-full gradient-accent text-white border-0"
                >
                  {shareToComm.isPending ? (
                    <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                  ) : (
                    <Share2 className="w-4 h-4 mr-2" />
                  )}
                  Share to Community
                </Button>

                <Button
                  onClick={handleExportPDF}
                  disabled={isExporting}
                  variant="outline"
                  className="w-full"
                  style={{ borderColor: 'var(--border)' }}
                >
                  {isExporting ? (
                    <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                  ) : (
                    <Download className="w-4 h-4 mr-2" />
                  )}
                  Export as File
                </Button>
              </div>
            </>
          ) : (
            <div className="space-y-4">
              <div className="p-4 rounded-2xl text-center" style={{ background: 'var(--background)' }}>
                <Check className="w-12 h-12 mx-auto mb-2 text-green-500" />
                <p className="font-semibold mb-2" style={{ color: 'var(--text-primary)' }}>
                  Plan Shared Successfully!
                </p>
              </div>

              <div>
                <Label style={{ color: 'var(--text-secondary)' }}>Shareable Link</Label>
                <div className="flex gap-2 mt-2">
                  <Input
                    value={shareUrl}
                    readOnly
                    style={{ background: 'var(--background)', borderColor: 'var(--border)', color: 'var(--text-primary)' }}
                  />
                  <Button onClick={handleCopyLink} className="gradient-accent text-white border-0">
                    <Link2 className="w-4 h-4" />
                  </Button>
                </div>
              </div>
            </div>
          )}
        </div>
      </DialogContent>
    </Dialog>
  );
}
